version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rotator          # 设置数据库用户名
      POSTGRES_PASSWORD: sdf3sjdkfds232jfklsle234  # 设置数据库密码
      POSTGRES_DB: rotator_database        # 初始化时创建的数据库名
    ports:
      - "8000:5432"  # 映射到主机的端口
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 数据持久化

volumes:
  postgres_data:
