version: '3'

services:
  web:
    build: .
    container_name: rotator_web
    ports:
      - "5000:5000"
    networks:
      - tor-net

  tor:
    image: goldy/tor-hidden-service
    container_name: tor_service
    restart: always
    networks:
      - tor-net
    volumes:
      - ./tor_data:/var/lib/tor
    environment:
      - HIDDENSERVICE_PORT=80
      - HIDDENSERVICE_TARGET=rotator_web:5000

networks:
  tor-net:
    driver: bridge
